name: CI

on:
  push:
    branches: [ "Feature/0824 workbanch", main, master ]
  pull_request:
    branches: [ "Feature/0824 workbanch", main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      # Fixed environment expected by imports/tests (no real DB connection required)
      APP_BIND_HOST: 127.0.0.1
      APP_BIND_PORT: '3011'
      DATABASE_URL: postgresql://127.0.0.1/newshub
      CI: "true"
      SKIP_DB_TESTS: "1"
      # Where to write progress file for linking (use /tmp for portability)
      PROGRESS_FILE: /tmp/linking.progress
      LINK_PROGRESS_FILE: /tmp/linking.progress
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run tests
        run: pytest -q
